crud_sort/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp/', include(('employee.urls','employee'),namespace='emp')),
]

employee/urls.py
from django.urls import path
from employee import  views 

urlpatterns = [
    path('',  views.EmployeeView.as_view(), name='employee'),
    path('createEmp', views.CreateEmployee.as_view(), name='create'),
    path('updateEmp', views.UpdateEmployee.as_view(), name='update'),
    path('deleteEmp', views.DeleteEmployee.as_view(), name='delete'),
]

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    #ID is autogenerated in Django so I am not taking this field here
    name = models.CharField(max_length=50, blank=True, null=True)
    roll_no = models.CharField(max_length=20, blank=True, null=True)
    class_name = models.CharField(max_length=30,blank=True, null=True)

employee/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView
from .models import Employee
from django.views.generic import View

# Create your views here.

class EmployeeView(ListView):
    model = Employee
    template_name = 'employee/emp.html'
    context_object_name = 'employees'



class CreateEmployee(View):
    def  get(self, request):
        name1 = request.GET.get('name', None)
        roll_no1 = request.GET.get('rollno', None)
        class_name1 = request.GET.get('classname', None)
        print('name', name1)
        print('roll_no', roll_no1)
        print('class_name1', class_name1)

        obj, created = Employee.objects.get_or_create(
            name = name1,
            roll_no = roll_no1,
            class_name = class_name1
        )

        user = {'id':obj.id,'name':obj.name,'roll_no':obj.roll_no,'class_name':obj.class_name}

        data = {
            'user': user
        }
        return JsonResponse(data)


class UpdateEmployee(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        name1 = request.GET.get('name', None)
        roll_no1 = request.GET.get('rollno', None)
        class_name1 = request.GET.get('classname', None)

        obj = Employee.objects.get(id=id1)
        obj.name = name1
        obj.roll_no = roll_no1
        obj.class_name = class_name1
        obj.save()

        user = {'id':obj.id,'name':obj.name,'roll_no':obj.roll_no,'class_name':obj.class_name}

        data = {
            'user': user
        }
        return JsonResponse(data)


class DeleteEmployee(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        Employee.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)

templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Title{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block stylesheet %}{% endblock stylesheet %}
  </head>
  <body>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
   <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
    {% block javascript %}
    {% endblock javascript%}
  </body>
</html>

templates/employee/emp.html
{% extends 'base.html' %}
{% load static %}

{% block title %}CRUD TASK{% endblock %}

{% block content %}
<div class="container">
    <h1 style="background-color: lightblue; text-align:center">Sort String Solutions LLP Task</h1>
    <div class="row">
      <div class="col-md-4 ">
        <h3 style='background: rgba(0, 128, 0, 0.1)'>ADD EMPLOYEE DATA</h3>
        <form id="addUser" action="">
          <div class="form-group">
            <input class="form-control" type="text" name="name" placeholder="Name" required>
          </div>
          <div class="form-group">
            <input class="form-control" type="text" name="classname" placeholder="className" required>
          </div>
          <div class="form-group">
            <input class="form-control" type="text" name="rollno" min="10" max="100" placeholder="RollNo" required>
          </div>
          <button class="btn btn-primary form-control" type="submit">SUBMIT</button>
        </form>
      </div>
      <div class="col-md-8">
        <h3 style='background: rgba(0, 128, 0, 0.2)'>LIST OF EMPLOYEES</h3>
        <table id="userTable" class="table table-striped">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Roll No.</th>
            <th colspan="3">Class Name</th>
          </tr>
          {% if employees %}
          {% for user in employees %}
          <tr id="user-{{user.id}}">
            <td class="userID userData" name="userid">{{user.id}}</td>
              <td class="userName userData" name="name">{{user.name}}</td>
              <td class="userRollNo userData" name="rollno">{{user.roll_no}}</td>
              <td class="userClassName userData" name="classname">{{user.class_name}}</td>
              <td align="center">
                  <button class="btn btn-success form-control" onClick="editUser({{user.id}})" data-toggle="modal" data-target="#myModal")">EDIT</button>
              </td>
              <td align="center">
                  <button class="btn btn-danger form-control" onClick="deleteUser({{user.id}})">DELETE</button>
              </td>
          </tr>
          {% endfor %}
          {% else %}
            No Users
          {% endif %}
        </table>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title" id="myModalLabel">Update User</h4>
        </div>
        <form id="updateUser" action="">
        <div class="modal-body">
            <input class="form-control" id="form-id" type="hidden" name="formId"/>
            <label for="name">Name</label>
            <input class="form-control" id="form-name" type="text" name="formName"/>
            <label for="rollno">Roll No</label>
            <input class="form-control" id="form-rollno" type="text" name="formRollno"/>
            <label for="className">className</label>
            <input class="form-control" id="form-classname" type="text" name="formClassname" min=10 max=100/>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" >Save changes</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block javascript %}

<script>
// Create 
$("form#addUser").submit(function() {
    var nameInput = $('input[name="name"]').val().trim();
    var RollNoInput = $('input[name="rollno"]').val().trim();
    var classNameInput = $('input[name="classname"]').val().trim();

    if (nameInput && RollNoInput && classNameInput) {
        // Create Ajax Call
        $.ajax({
            url: '{% url "emp:create" %}',
            data: {
                'name': nameInput,
                'rollno': RollNoInput,
                'classname': classNameInput
            },
            dataType: 'json',
            success: function (data) {
                if (data.user) {
                  appendToUsrTable(data.user);
                }
            }
        });
      } else {
        alert("All fields must have a valid value.");
    }
    $('form#addUser').trigger("reset");
    return false;
});
function appendToUsrTable(user) {
  $("#userTable > tbody:last-child").append(`
        <tr id="user-${user.id}">
           <td class="userid" name="userid">${user.id}</td>
            <td class="userName" name="name">${user.name}</td>
            '<td class="userRollNo" name="rollno">${user.roll_no}</td>
            '<td class="userClassName" name="classname">${user.class_name}</td>
            '<td align="center">
                <button class="btn btn-success form-control" onClick="editUser(${user.id})" data-toggle="modal" data-target="#myModal")">EDIT</button>
            </td>
            <td align="center">
                <button class="btn btn-danger form-control" onClick="deleteUser(${user.id})">DELETE</button>
            </td>
        </tr>
    `);
}


// Create 
$("form#updateUser").submit(function() {
    var idInput = $('input[name="formId"]').val().trim();
    var nameInput = $('input[name="formName"]').val().trim();
    var rollnoInput = $('input[name="formRollno"]').val().trim();
    var classnameInput = $('input[name="formClassname"]').val().trim();
    if (nameInput && rollnoInput && classnameInput) {
        // Create Ajax Call
        $.ajax({
            url: '{% url "emp:update" %}',
            data: {
                'id': idInput,
                'name': nameInput,
                'rollno': rollnoInput,
                'classname': classnameInput
            },
            dataType: 'json',
            success: function (data) {
                if (data.user) {
                  updateToUserTabel(data.user);
                }
            }
        });
       } else {
        alert("All fields must have a valid value.");
    }
    $('form#updateUser').trigger("reset");
    $('#myModal').modal('hide');
    return false;
});

// Update 
function editUser(id) {
  if (id) {
    tr_id = "#user-" + id;
    name = $(tr_id).find(".userName").text();
    address = $(tr_id).find(".userAddress").text();
    age = $(tr_id).find(".userAge").text();
    $('#form-id').val(id);
    $('#form-name').val(name);
    $('#form-address').val(address);
    $('#form-age').val(age);
  }
}
function updateToUserTabel(user){
    $("#userTable #user-" + user.id).children(".userData").each(function() {
        var attr = $(this).attr("name");
        if (attr == "name") {
          $(this).text(user.name);
        } else if (attr == "rollno") {
          $(this).text(user.roll_no);
        } else if (attr == "classname") {
          $(this).text(user.class_name);
        } else{
            $(this).text(user.id);
        }
      });
}




// Delete 
function deleteUser(id) {
  var action = confirm("Are you sure you want to delete data of this employee?");
  if (action != false) {
    $.ajax({
        url: '{% url "emp:delete" %}',
        data: {
            'id': id,
        },
        dataType: 'json',
        success: function (data) {
            if (data.deleted) {
              $("#userTable #user-" + id).remove();
            }
        }
    });
  }
}

</script>

{% endblock javascript %}